# Generated by Django 4.1.5 on 2023-04-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_voters_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='data',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='signer_address',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
