# Generated by Django 4.1.5 on 2023-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_block_data_block_signer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
